In [ ]:
#Libraries
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
dataFrame = pd.read_csv("Data/Churn_Modelling.csv") #Importing dataset
dataFrame

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [ ]:
dataFrame.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
dataFrame.drop(columns=["RowNumber","CustomerId","Surname"], inplace=True)
dataFrame.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [ ]:
dataFrame.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
#Encoding categorical columns
le= LabelEncoder()
dataFrame["Geography"]=le.fit_transform(dataFrame["Geography"])
dataFrame["Gender"]= le.fit_transform(dataFrame["Gender"])
print(dataFrame["Gender"])
print(dataFrame["Geography"])

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64
0       0
1       2
2       0
3       0
4       2
       ..
9995    0
9996    0
9997    0
9998    1
9999    0
Name: Geography, Length: 10000, dtype: int64


In [ ]:
x= dataFrame.iloc[:,:10].values 
y= dataFrame.iloc[:,-1].values

In [ ]:
#OneHotEncoding "Geography" column
ohe=ColumnTransformer([("ohe", OneHotEncoder(dtype=float),[1])], 
                      remainder="passthrough")
x=ohe.fit_transform(x)

In [ ]:
#Spliting dataset and Standardization data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=5)
sc= StandardScaler()
X_train= sc.fit_transform(x_train)
X_test= sc.fit_transform(x_test)

In [ ]:
X_train

array([[ 0.58539335, -0.58539335,  1.00119474, ...,  0.65488632,
        -1.02631631, -0.49076078],
       [ 0.58539335, -0.58539335,  1.00119474, ..., -1.52698257,
        -1.02631631,  1.59170218],
       [ 0.58539335, -0.58539335, -0.99880668, ...,  0.65488632,
         0.97435848, -0.34479182],
       ...,
       [ 0.58539335, -0.58539335,  1.00119474, ...,  0.65488632,
        -1.02631631, -1.50953432],
       [ 0.58539335, -0.58539335,  1.00119474, ..., -1.52698257,
         0.97435848,  1.26969153],
       [-1.7082531 ,  1.7082531 , -0.99880668, ...,  0.65488632,
        -1.02631631, -1.08036997]])

In [ ]:
#Creating Model
annClassifier= Sequential()
annClassifier.add(Dense(6, activation="relu"))
annClassifier.add(Dense(6, activation="relu"))
#output layer
annClassifier.add(Dense(1, activation="sigmoid"))

annClassifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
annClassifier.fit(X_train, y_train, batch_size= 50, epochs=100)

Epoch 1/100
134/134 [==============================] - 0s 998us/step - loss: 0.6174 - accuracy: 0.7097
Epoch 2/100
134/134 [==============================] - 0s 1ms/step - loss: 0.5086 - accuracy: 0.7955
Epoch 3/100
134/134 [==============================] - 0s 1ms/step - loss: 0.4711 - accuracy: 0.7963
Epoch 4/100
134/134 [==============================] - 0s 1ms/step - loss: 0.4510 - accuracy: 0.7963
Epoch 5/100
134/134 [==============================] - 0s 1ms/step - loss: 0.4359 - accuracy: 0.7963
Epoch 6/100
134/134 [==============================] - 0s 1ms/step - loss: 0.4231 - accuracy: 0.7979
Epoch 7/100
134/134 [==============================] - 0s 1ms/step - loss: 0.4095 - accuracy: 0.8066
Epoch 8/100
134/134 [==============================] - 0s 1ms/step - loss: 0.3975 - accuracy: 0.8131
Epoch 9/100
134/134 [==============================] - 0s 984us/step - loss: 0.3887 - accuracy: 0.8170
Epoch 10/100
134/134 [==============================] - 0s 1ms/step - loss: 0.3822 - ac

In [ ]:
y_pred = annClassifier.predict(X_test)
y_pred

array([[0.04012001],
       [0.09045723],
       [0.11919066],
       ...,
       [0.02810419],
       [0.05606207],
       [0.07219261]], dtype=float32)

In [ ]:
y_pred= y_pred > 0.5
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
#Result
cm= confusion_matrix(y_test,y_pred)
cm

array([[2512,  116],
       [ 358,  314]])